const ListingsAPI = {
    listings: [
      { number: 1, name: "1 = House in West California", price:"$ 505,000", SixDigitPinAccess: 234123, descriptionLite: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", descriptionFull: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", FacilitiesAll: {'bedrooms': 5, 'bathrooms': 3, 'kitchens': 2, 'TotalPlotArea': '1800 sq mtrs'}, AminitiesRich: ['HotTub', 'Garden Area', 'Swimming Pool', 'Patio', 'Hard Wood Flooring', 'Many More . . . '], threeAssets: {'ObjLocation': 'someUnknown.obj', 'MtlLocation': 'someUnknown.mtl', 'zoomFactorySettings': 2}, react360View: {'InnerView' : 'Its URL location in the same hosting domain'}, propertyOnMap:{'lat': "37.23", "lon": "-10.56"}, additionalDetails:{'bedroom features': 'Main Floor Master Bedroom, Walk-In Closet', 'dining area': 'Breakfast Counter/Bar, Living/Dining Combo', 'doors & windows': 'Bay Window', 'entry location': 'Mid Level', 'floors': 'Raised Foundation, Vinyl Tile, Wall-to-Wall Carpet, Wood'}},



      { number: 2, name: "2 = Villa in Milano", price:"$ 505,000", SixDigitPinAccess: 234123, descriptionLite: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", descriptionFull: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", FacilitiesAll: {'bedrooms': 5, bathrooms: 3, kitchens: 2, TotalPlotArea: '1800 sq mtrs'}, AminitiesRich: ['HotTub', 'Garden Area', 'Swimming Pool', 'Patio', 'Hard Wood Flooring', 'Many More . . . '], threeAssets:{'ObjLocation': 'someUnknown.obj', 'MtlLocation': 'someUnknown.mtl', 'zoomFactorySettings': 2}, react360View: {'InnerView' : 'Its URL location in the same hosting domain'}, propertyOnMap:{'lat': "37.23", "lon": "-10.56"}, additionalDetails:{'bedroom features': 'Main Floor Master Bedroom, Walk-In Closet', 'dining area': 'Breakfast Counter/Bar, Living/Dining Combo', 'doors & windows': 'Bay Window', 'entry location': 'Mid Level', 'floors': 'Raised Foundation, Vinyl Tile, Wall-to-Wall Carpet, Wood'}},




      { number: 3, name: "3 = Villa in West Barcelona", price:"$ 505,000", SixDigitPinAccess: 234123, descriptionLite: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", descriptionFull: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", FacilitiesAll: {'bedrooms': 5, bathrooms: 3, kitchens: 2, TotalPlotArea: '1800 sq mtrs'}, AminitiesRich: ['HotTub', 'Garden Area', 'Swimming Pool', 'Patio', 'Hard Wood Flooring', 'Many More . . . '], threeAssets:{'ObjLocation': 'someUnknown.obj', 'MtlLocation': 'someUnknown.mtl', 'zoomFactorySettings': 2}, react360View: {'InnerView' : 'Its URL location in the same hosting domain'}, propertyOnMap:{'lat': "37.23", "lon": "-10.56"}, additionalDetails:{'bedroom features': 'Main Floor Master Bedroom, Walk-In Closet', 'dining area': 'Breakfast Counter/Bar, Living/Dining Combo', 'doors & windows': 'Bay Window', 'entry location': 'Mid Level', 'floors': 'Raised Foundation, Vinyl Tile, Wall-to-Wall Carpet, Wood'}},




      { number: 4, name: "4 = Villa in Milano", price:"$ 505,000", SixDigitPinAccess: 234123, descriptionLite: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", descriptionFull: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", FacilitiesAll: {'bedrooms': 5, bathrooms: 3, kitchens: 2, TotalPlotArea: '1800 sq mtrs'}, AminitiesRich: ['HotTub', 'Garden Area', 'Swimming Pool', 'Patio', 'Hard Wood Flooring', 'Many More . . . '], threeAssets:{'ObjLocation': 'someUnknown.obj', 'MtlLocation': 'someUnknown.mtl', 'zoomFactorySettings': 2}, react360View: {'InnerView' : 'Its URL location in the same hosting domain'}, propertyOnMap:{'lat': "37.23", "lon": "-10.56"}, additionalDetails:{'bedroom features': 'Main Floor Master Bedroom, Walk-In Closet', 'dining area': 'Breakfast Counter/Bar, Living/Dining Combo', 'doors & windows': 'Bay Window', 'entry location': 'Mid Level', 'floors': 'Raised Foundation, Vinyl Tile, Wall-to-Wall Carpet, Wood'}},




      { number: 5, name: "5 = Villa in West Barcelona", price:"$ 505,000", SixDigitPinAccess: 234123, descriptionLite: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", descriptionFull: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", FacilitiesAll: {'bedrooms': 5, bathrooms: 3, kitchens: 2, TotalPlotArea: '1800 sq mtrs'}, AminitiesRich: ['HotTub', 'Garden Area', 'Swimming Pool', 'Patio', 'Hard Wood Flooring', 'Many More . . . '], threeAssets:{'ObjLocation': 'someUnknown.obj', 'MtlLocation': 'someUnknown.mtl', 'zoomFactorySettings': 2}, react360View: {'InnerView' : 'Its URL location in the same hosting domain'}, propertyOnMap:{'lat': "37.23", "lon": "-10.56"}, additionalDetails:{'bedroom features': 'Main Floor Master Bedroom, Walk-In Closet', 'dining area': 'Breakfast Counter/Bar, Living/Dining Combo', 'doors & windows': 'Bay Window', 'entry location': 'Mid Level', 'floors': 'Raised Foundation, Vinyl Tile, Wall-to-Wall Carpet, Wood'}},




      { number: 6, name: "6 = House in Holloywood Hills", price:"$ 505,000", SixDigitPinAccess: 234123, descriptionLite: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", descriptionFull: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", FacilitiesAll: {'bedrooms': 5, bathrooms: 3, kitchens: 2, TotalPlotArea: '1800 sq mtrs'}, AminitiesRich: ['HotTub', 'Garden Area', 'Swimming Pool', 'Patio', 'Hard Wood Flooring', 'Many More . . . '], threeAssets:{'ObjLocation': 'someUnknown.obj', 'MtlLocation': 'someUnknown.mtl', 'zoomFactorySettings': 2}, react360View: {'InnerView' : 'Its URL location in the same hosting domain'}, propertyOnMap:{'lat': "37.23", "lon": "-10.56"}, additionalDetails:{'bedroom features': 'Main Floor Master Bedroom, Walk-In Closet', 'dining area': 'Breakfast Counter/Bar, Living/Dining Combo', 'doors & windows': 'Bay Window', 'entry location': 'Mid Level', 'floors': 'Raised Foundation, Vinyl Tile, Wall-to-Wall Carpet, Wood'}},




      { number: 7, name: "7 = Luxurious beach in Port of Maimi", price:"$ 505,000", SixDigitPinAccess: 234123, descriptionLite: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", descriptionFull: "Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.", FacilitiesAll: {'bedrooms': 5, bathrooms: 3, kitchens: 2, TotalPlotArea: '1800 sq mtrs'}, AminitiesRich: ['HotTub', 'Garden Area', 'Swimming Pool', 'Patio', 'Hard Wood Flooring', 'Many More . . . '], threeAssets:{'ObjLocation': 'someUnknown.obj', 'MtlLocation': 'someUnknown.mtl', 'zoomFactorySettings': 2}, react360View: {'InnerView' : 'Its URL location in the same hosting domain'}, propertyOnMap:{'lat': "37.23", "lon": "-10.56"}, additionalDetails:{'bedroom features': 'Main Floor Master Bedroom, Walk-In Closet', 'dining area': 'Breakfast Counter/Bar, Living/Dining Combo', 'doors & windows': 'Bay Window', 'entry location': 'Mid Level', 'floors': 'Raised Foundation, Vinyl Tile, Wall-to-Wall Carpet, Wood'}},




    ],
    
    all: function() { return this.listings },

    get: function(id) {
      const oneListingItem = p => p.number === id
      return this.listings.find(oneListingItem)
    },

    featuredProperties: function() {
      return this.listings.slice(-3, )
    },

  }
  
  export default ListingsAPI